# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "chef/debian-7.7"
    config.vm.hostname = "maestro-dev"
    config.vm.box_check_update = false
    config.vm.network "private_network", ip: "192.168.42.2"
    config.vm.synced_folder "../", "/src/maestro"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    config.vm.provision "shell", path: "init.sh"
end

